const cfg=window.SITE_DATA.supabase;let token=sessionStorage.getItem("dts_token")||"";const loginView=document.getElementById("loginView"),portalView=document.getElementById("portalView"),loginForm=document.getElementById("loginForm"),loginMessage=document.getElementById("loginMessage"),portalMessage=document.getElementById("portalMessage"),reservationList=document.getElementById("reservationList"),logoutButton=document.getElementById("logoutButton");
const h=(extra={})=>({apikey:cfg.publishableKey,Authorization:`Bearer ${token}`,"Content-Type":"application/json",...extra});
function msg(el,t,e=false){el.className=e?"notice error":"notice";el.textContent=t}
async function login(email,password){const r=await fetch(`${cfg.url}/auth/v1/token?grant_type=password`,{method:"POST",headers:{apikey:cfg.publishableKey,"Content-Type":"application/json"},body:JSON.stringify({email,password})});const b=await r.json();if(!r.ok)throw new Error(b.msg||"Could not sign in.");token=b.access_token;sessionStorage.setItem("dts_token",token)}
async function load(){const r=await fetch(`${cfg.url}/rest/v1/reservations?select=*,properties(name)&order=created_at.desc`,{headers:h()});if(!r.ok)throw new Error(await r.text());return r.json()}
async function patch(id,changes){const r=await fetch(`${cfg.url}/rest/v1/reservations?id=eq.${id}`,{method:"PATCH",headers:h({Prefer:"return=minimal"}),body:JSON.stringify(changes)});if(!r.ok)throw new Error(await r.text())}
async function addPayment(id,amount,method){let r=await fetch(`${cfg.url}/rest/v1/payments`,{method:"POST",headers:h({Prefer:"return=minimal"}),body:JSON.stringify({reservation_id:id,amount:Number(amount),payment_method:method,received_at:new Date().toISOString()})});if(!r.ok)throw new Error(await r.text());await patch(id,{payment_status:"paid",payment_method:method,amount_received:Number(amount),payment_received_at:new Date().toISOString(),status:"booked"})}
const fd=v=>new Date(`${v}T12:00:00`).toLocaleDateString("en-US",{month:"short",day:"numeric",year:"numeric"});
function card(r){return `<article class="card res" data-id="${r.id}"><div><h2>${r.guest_name}</h2><div class="meta"><b>${r.properties?.name||"Property"}</b><br>${fd(r.arrival_date)} – ${fd(r.departure_date)}<br>${r.guest_email||""}${r.guest_phone?` · ${r.guest_phone}`:""}<br>${r.adults||0} guest(s)${r.dogs?` · ${r.dogs} dog(s)${r.dog_names?` (${r.dog_names})`:""}`:""}</div><span class="badge">${(r.status||"pending").replaceAll("_"," ")}</span><span class="badge">payment: ${(r.payment_status||"waiting").replaceAll("_"," ")}</span>${r.hold_expires_at?`<div class="meta" style="margin-top:8px">Hold expires: ${new Date(r.hold_expires_at).toLocaleString()}</div>`:""}<div class="money"><b>Log payment</b><div class="row" style="margin-top:8px"><input type="number" step=".01" placeholder="Amount" data-amt><select data-method><option value="zelle">Zelle</option><option value="venmo">Venmo</option><option value="credit_card">Credit card</option><option value="check">Check</option></select><button data-action="paid">Mark paid</button></div></div></div><div class="actions"><button data-action="accept">Accept · 24h hold</button><button data-action="decline">Decline</button></div></article>`}
async function refresh(){try{const rows=await load();reservationList.innerHTML=rows.length?rows.map(card).join(""):'<div class="card">No reservation requests yet.</div>'}catch(e){msg(portalMessage,e.message,true)}}
function show(){loginView.hidden=true;portalView.hidden=false;refresh()}function signout(){token="";sessionStorage.removeItem("dts_token");portalView.hidden=true;loginView.hidden=false}
loginForm.onsubmit=async e=>{e.preventDefault();const f=new FormData(loginForm);try{await login(f.get("email"),f.get("password"));show()}catch(err){msg(loginMessage,err.message,true)}};
logoutButton.onclick=signout;
reservationList.onclick=async e=>{const b=e.target.closest("button[data-action]");if(!b)return;const c=b.closest("[data-id]"),id=c.dataset.id,a=b.dataset.action;try{if(a==="accept"){await patch(id,{status:"pending_payment",hold_expires_at:new Date(Date.now()+86400000).toISOString()});msg(portalMessage,"Accepted. 24-hour hold started.")}if(a==="decline"){await patch(id,{status:"declined",hold_expires_at:null});msg(portalMessage,"Declined.")}if(a==="paid"){const amt=c.querySelector("[data-amt]").value,m=c.querySelector("[data-method]").value;if(!amt)throw new Error("Enter the amount.");await addPayment(id,amt,m);msg(portalMessage,"Payment logged.")}await refresh()}catch(err){msg(portalMessage,err.message,true)}};
if(token)show();